spring:
  cloud:
    config:
      server:        git:          uri: https://github.com/badrinath-danave/environment-variable-repo
        bootstrap: true  application:    name: SpringBoot-Cloud-Config-Server  profiles:    active: native


server:  port: 8888

 